[package]
name = "wwbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bincode = "1.3"
serde_json = "1.0"
rand = "0.8"
once_cell = "1.17"
#include-flate = "0.1"
